import { app, BrowserWindow, ipcMain, Tray, Menu, globalShortcut, clipboard, dialog, nativeImage, shell } from 'electron';
import path from 'path';
import { exec, spawn, ChildProcess } from 'child_process';
import fs from 'fs';
import * as readline from 'readline';
import { t, detectLocale, Locale } from '../src/i18n';

let win: BrowserWindow | null = null;
let tray: Tray | null = null;
let crispAsrProcess: ChildProcess | null = null;

let isRecording = false;
let interimTranscript = "";

// Default settings
const settingsPath = path.join(app.getPath('userData'), 'crisp_settings.json');
let settings = {
  backend: 'cpu',
  micDevice: 'default',
  threads: 4,
  gpuId: 0,
  language: 'auto',
  hotkey: 'CommandOrControl+Shift+R',
  mode: 'lowest-latency',
  autoStart: false,
  autoPaste: false,
  locale: '' as string // interface language; detected from OS on first launch
};

// Current interface locale (falls back to English if unset).
function curLocale(): Locale {
  return ((settings.locale as string) || 'en') as Locale;
}

// --- BASE64 ICONS FOR TRAY ---
// 32x32 Retro grille microphone. White = outline + grille slot lines + stem.
// Interior (between slots) is BLACK when idle, RED when recording.
// Generated by gen-icons.js — regenerate with: node gen-icons.js
const IDLE_ICON_B64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAASklEQVR4nO3SsQ0AMAgDQfZfOilYAEe2SPGWqDmQqwgZ5oiJGMQxbu6LpLF+4QvAS6yA9Q8AoAMA6AAAOgBgvQOrgAkqugwAgGQuS3PxKyxOok0AAAAASUVORK5CYII=";
const REC_ICON_B64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAT0lEQVR4nO3SwQkAMAhDUadx/6G6h6UbqETs4Qc8+5SYEZJMFCMHHPeojHT5u6gKkH7hC0AnUsD6BwDQAQB0AAAdALDegVVABjW6DACAyVyXDcb6Sb1OQAAAAABJRU5ErkJggg==";

const IDLE_ICON = nativeImage.createFromDataURL(IDLE_ICON_B64);
const REC_ICON = nativeImage.createFromDataURL(REC_ICON_B64);


function loadSettings() {
  if (fs.existsSync(settingsPath)) {
    try {
      const data = fs.readFileSync(settingsPath, 'utf8');
      settings = { ...settings, ...JSON.parse(data) };
      app.setLoginItemSettings({ openAtLogin: settings.autoStart });
    } catch(e) { console.error("Could not load settings", e); }
  }
  // First launch: detect the interface language from the OS locale.
  // If the Windows locale is not supported, detectLocale falls back to 'en'.
  if (!settings.locale) {
    settings.locale = detectLocale(app.getLocale());
    try { fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2)); } catch(_) {}
  }
}

function saveSettings() {
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
  app.setLoginItemSettings({ openAtLogin: settings.autoStart });
  registerHotkeys();
  // Keep the tray menu checkboxes (autoPaste, autoStart, mode radios) in sync.
  rebuildTrayMenu();
  // Notify the renderer so the UI toggle button and the settings modal
  // checkbox reflect changes made from the tray menu.
  emitSettingsUpdated();
}

// Emit the current settings to the renderer. Used whenever settings change
// from a source OTHER than the renderer itself (tray menu, hotkey, etc.) so
// the UI stays in sync.
function emitSettingsUpdated() {
  win?.webContents.send('settings-updated', { ...settings });
}

// Toggle auto-paste from a single entry point (tray menu, IPC, etc.).
// This keeps the tray checkbox, the UI toggle button, and the settings modal
// checkbox all synchronized.
function setAutoPaste(value: boolean) {
  settings.autoPaste = !!value;
  saveSettings();
}

function registerHotkeys() {
  globalShortcut.unregisterAll();
  if (settings.hotkey) {
    globalShortcut.register(settings.hotkey, () => {
      if (isRecording) {
        stopMicrophone(); // Uses same logic as clicking Stop
      } else {
        startMicrophone(); // Uses same logic as clicking Start
      }
    });
  }
}

function rebuildTrayMenu() {
  if (!tray) return;
  const L = curLocale();
  const ctxMenu = Menu.buildFromTemplate([
    { label: t(L, 'tray.open'), click: () => win?.show() },
    {
      label: t(L, 'tray.modeLowest'),
      type: 'radio',
      checked: settings.mode === 'lowest-latency',
      click: () => { settings.mode = 'lowest-latency'; saveSettings(); }
    },
    {
      label: t(L, 'tray.modeBest'),
      type: 'radio',
      checked: settings.mode === 'best-quality',
      click: () => { settings.mode = 'best-quality'; saveSettings(); }
    },
    { type: 'separator' },
    {
      label: t(L, 'tray.autoPaste'),
      type: 'checkbox',
      checked: settings.autoPaste,
      click: (item) => { setAutoPaste(item.checked); }
    },
    {
      label: t(L, 'tray.autoStart'),
      type: 'checkbox',
      checked: settings.autoStart,
      click: (item) => { settings.autoStart = item.checked; saveSettings(); }
    },
    { label: t(L, 'tray.exit'), click: () => {
      win?.destroy(); // destroy avoids the close-to-tray logic
      app.quit();
    }}
  ]);
  tray.setContextMenu(ctxMenu);
}

function createTray() {
  tray = new Tray(IDLE_ICON);
  tray.setToolTip('AutoSpeechWriter');
  rebuildTrayMenu();
  tray.on('click', () => {
    win?.isVisible() ? win.hide() : win?.show();
  });
}

function createWindow() {
  win = new BrowserWindow({
    width: 600,
    height: 700,
    frame: false,
    resizable: true,
    title: 'AutoSpeechWriter',
    icon: path.join(__dirname, '..', 'build', 'icon.png'), // app/taskbar icon (microphone)
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      backgroundThrottling: false // Keep running smartly when minimized
    }
  });

  // Depending on env, load URL or local file
  if (process.env.VITE_DEV_SERVER_URL) {
    win.loadURL(process.env.VITE_DEV_SERVER_URL);
  } else {
    win.loadFile(path.join(__dirname, '../dist/index.html'));
  }

  // Intercept close to minimize to tray
  win.on('close', (e) => {
    e.preventDefault();
    win?.hide();
  });
}

const INFO_PREFIXES = [
  "crispasr", "sensevoice", "parakeet", "whisper", "moonshine",
  "voxtral", "qwen", "canary", "auto-detected", "loading", "usage", "system memory",
  "ggml", "backend", "buffer", "model", "encoder", "decoder", "vulkan", "cuda",
  "whisper_init", "whisper_model_load", "whisper_backend", "whisper_print_timings",
  "[", "$", "=", "-", "POST", "Ping", "HTTP", "✓", "✗", "готов", "работает", 
  "запуск", "сервер", "loaded", "processing", "transcribed", "main:"
];

function isResultLine(text: string): boolean {
  if (!text) return false;
  const low = text.toLowerCase();
  for (const p of INFO_PREFIXES) {
    if (low.startsWith(p)) {
      return false;
    }
  }
  return true;
}

let micLastUtteranceId = -1;

// Emulate backend logic processing
function processAsrLogLine(line: string, mode: 'mic' | 'file') {
  if (!win) return;
  const trimmed = line.trim();
  if (trimmed.length === 0) return;

  if (mode === 'mic') {
    if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
      try {
        const parsed = JSON.parse(trimmed);
        
        if (parsed.type === 'silence') {
          win.webContents.send('silence-state', true);
          setTimeout(() => win?.webContents.send('silence-state', false), 1500);
          return;
        }

        if (parsed.type && parsed.text !== undefined) {
          const utteranceId = parsed.utterance_id || 0;
          const text = parsed.text.trim();
          
          if (parsed.type === 'partial') {
            win.webContents.send('transcription-update', text, false);
            return;
          } else if (parsed.type === 'final') {
            if (utteranceId > micLastUtteranceId) {
              if (text) {
                micLastUtteranceId = utteranceId;
                // Accumulate finalized text so the non-autoPaste path can copy
                // the full transcript to the clipboard when recording stops.
                interimTranscript += text + ' ';
                // Always update the UI transcript (gray partial / white final).
                win.webContents.send('transcription-update', text, true);
                win.webContents.send('log-update', `[ФИНАЛ] ${text}\n`);
                // AUTO-PASTE: fires if EITHER settings.autoPaste (tray mode)
                // OR uiAutoPaste (interface mode) is ON. The window is NEVER
                // hidden — see the comment block above executePasteIntoActiveApp.
                if (settings.autoPaste || uiAutoPaste) {
                  executePasteIntoActiveApp(text + ' ');
                }
              } else {
                win.webContents.send('transcription-update', '', false);
              }
            }
            return;
          }
        }
      } catch (e) {
        // Fall through
      }
    }
  }

  // Not JSON, or file mode
  const isRes = isResultLine(trimmed);
  if (isRes) {
    win.webContents.send('log-update', trimmed + '\n');
    // In mic mode, the transcript is driven EXCLUSIVELY by JSON partial/final
    // messages. crispasr echoes each finalized phrase both as a JSON
    // {"type":"final"} line AND as a plain-text line. If we appended the
    // plain-text echo here, every phrase would appear twice in the UI.
    // (The Python GUI avoids this because _update_mic_display() rebuilds the
    //  text widget from mic_finalized_text on every update, wiping duplicates.)
    // Electron's frontend uses an append-only array, so we must skip here.
    if (mode !== 'mic') {
      win.webContents.send('transcription-update', trimmed, true);
    }
  } else {
    win.webContents.send('log-update', trimmed + '\n');
  }
}

function startCrispBackendInstance(mode: 'file' | 'mic', payload?: string) {
  // Guard: if a backend process is already running, kill it synchronously and
  // clear the reference BEFORE spawning a new one. This prevents two parallel
  // crispasr.exe instances from grabbing the microphone simultaneously
  // (which was the root cause of duplicated final text).
  if (crispAsrProcess) {
    try {
      // 'SIGKILL' forces immediate termination on Windows (via taskkill).
      // A plain kill() maps to SIGTERM which the backend may not handle promptly.
      crispAsrProcess.kill('SIGKILL');
    } catch (e) {
      console.error('Failed to kill previous backend:', e);
    }
    crispAsrProcess = null;
  }

  // Construct binary paths based on requested backend settings mapping
  const basePath = app.isPackaged ? process.resourcesPath : path.join(__dirname, '..');
  const dirName = `crispasr-windows-x86_64-${settings.backend}`;
  const binPath = path.join(basePath, dirName, 'crispasr.exe');
  const modelPath = path.join(basePath, 'models-cache', 'parakeet-tdt-0.6b-v3-q4_k.gguf');
  const ffmpegBinPath = path.join(basePath, 'ffmpeg', 'bin');
  const ffmpegRootPath = path.join(basePath, 'ffmpeg');

  // Verify binary exists, fallback to simulating the logic if path missing in dev
  if (!fs.existsSync(binPath)) {
    console.log(`[SIMULATED ASR] Backend binary not found at ${binPath}. Simulating output.`);
    win?.webContents.send('log-update', `[SYSTEM] Backend not found at ${binPath}\n`);
    // Dev only mock streaming
    setTimeout(() => { processAsrLogLine('{"type":"silence","t":1.000}', mode); }, 1000);
    setTimeout(() => { processAsrLogLine('Recognized test transcription.', mode); stopMicrophone(); }, 3000);
    return;
  }

  const args = [
    '-m', modelPath,
    '-t', settings.threads.toString(),
    '-dev', settings.gpuId.toString()
  ];

  if (settings.language) {
    args.push('-l', settings.language);
  }

  // Force json output so we can parse it
  args.push('--stream-json');

  // VAD is REQUIRED for phrase segmentation: without it the backend cannot
  // detect phrase boundaries and will never emit {type:"final"} messages.
  // The working Python GUI always passes --vad.
  args.push('--vad');

  // Silence threshold for finalizing a phrase (matching Python GUI).
  // NOTE: --stream-final-mode is intentionally NOT used — the working Python
  // version does not pass it, and it can alter how/whether finals are emitted.
  if (settings.mode === 'lowest-latency') {
    args.push('--stream-final-on-silence-ms', '40');
  } else {
    args.push('--stream-final-on-silence-ms', '1250');
  }

  if (mode === 'mic') {
    // Use --mic (phrase-by-phrase with VAD) instead of --live (continuous).
    // --mic mode emits {type:"final"} on each detected phrase boundary,
    // which is exactly the gray-partial → white-final behaviour we need.
    // --live only streams partials indefinitely and never finalizes.
    args.push('--mic');
  } else if (mode === 'file' && payload) {
    args.push('-f', payload);
  }
  
  if (mode === 'mic') {
    micLastUtteranceId = -1;
  }

  win?.webContents.send('log-update', `[SYSTEM] Starting backend: ${binPath} \n[SYSTEM] Args: ${args.join(' ')}\n`);

  try {
    const env = Object.assign({}, process.env);
    // Add ffmpeg to PATH depending on structure (usually ffmpeg/bin)
    env.PATH = `${ffmpegBinPath}${path.delimiter}${ffmpegRootPath}${path.delimiter}${env.PATH}`;

    console.log(`===DIAG=== [Main PID:${process.pid}] about to spawn crispasr.exe (mode=${mode})`);
    crispAsrProcess = spawn(binPath, args, {
      cwd: path.dirname(binPath),
      env: env
    });
    const childPid = crispAsrProcess.pid;
    console.log(`===DIAG=== [Main PID:${process.pid}] SPAWNED crispasr.exe child PID=${childPid}`);
    
    if (crispAsrProcess.stdout) {
      // Use readline so that JSON lines split across chunk boundaries are
      // correctly reassembled. The previous data.split('\n') approach silently
      // dropped any line that happened to span two 'data' events — which
      // disproportionately affected longer 'final' messages.
      const rl = readline.createInterface({
        input: crispAsrProcess.stdout,
        crlfDelay: Infinity
      });
      rl.on('line', (line: string) => {
        processAsrLogLine(line, mode);
      });
    }
    
    crispAsrProcess.stderr?.on('data', (err) => {
      const msg = err.toString();
      console.log('Backend Error:', msg);
      // Send backend errors to UI so user knows what's failing!
      win?.webContents.send('log-update', `[LOG] ${msg}`);
    });
    
    crispAsrProcess.on('close', (code) => {
      console.log(`===DIAG=== [Main PID:${process.pid}] child PID=${childPid} EXITED code=${code}`);
      console.log(`Backend process exited with code ${code}`);
      // Clear the reference so a future start (mic or file) isn't blocked by
      // a stale pointer to a dead process.
      crispAsrProcess = null;
      win?.webContents.send('log-update', `\n[SYSTEM] Backend process exited with code ${code}\n`);
      // Stop recording UI state if it died
      if (isRecording) {
        stopMicrophone();
      }
    });
    
  } catch(e: any) {
    console.error("Failed to spawn CrispASR:", e);
    win?.webContents.send('log-update', `\n[SYSTEM ERROR] Failed to spawn process: ${e.message}\n`);
  }
}

// ---------------------------------------------------------------------------
// AUTO-PASTE: writes text to the clipboard and emulates Ctrl+V so the text
// lands in whatever application currently has the keyboard focus.
//
// Two INDEPENDENT triggers control whether auto-paste fires per finalized
// phrase:
//   1. settings.autoPaste — "tray mode". Synchronized between the tray menu
//                           checkbox and the Settings modal checkbox.
//   2. uiAutoPaste        — "interface mode". Toggled by the footer button
//                           in the main UI. INDEPENDENT of settings.autoPaste.
//
// Auto-paste fires if EITHER is ON. The Electron window is NEVER hidden here:
//   - If the app is in the tray, there is nothing to hide.
//   - If the user is pasting from the visible window, they want it visible
//     (e.g. to watch the gray partial text). They manage focus themselves —
//     either minimize, or just click into the target app and place the cursor.
// ---------------------------------------------------------------------------
let pasteInProgress = false;
let uiAutoPaste = false;

function executePasteIntoActiveApp(text: string) {
  if (!text) return;
  // Prevent overlapping paste operations: if a previous paste is still in
  // flight, drop this one (the next final will paste the accumulated text).
  if (pasteInProgress) {
    console.log('===DIAG=== paste already in progress, skipping');
    return;
  }
  pasteInProgress = true;

  // Step 1: write to clipboard (100% reliable, native Electron API).
  clipboard.writeText(text);

  // Step 2: wait briefly, then send Ctrl+V to whatever app currently has focus.
  // (The window is intentionally NOT hidden — see the comment block above.)
  setTimeout(() => {
    // Use keybd_event via P/Invoke instead of WScript.Shell.SendKeys.
    // SendKeys is known to leave the Ctrl modifier "stuck" — it sends keydown
    // but the keyup is unreliable, so Ctrl stays logically pressed. Symptoms:
    //   - Notepad caret stops blinking (caret stays solid while Ctrl held)
    //   - Firefox shows its F7 caret-browsing prompt instead of pasting
    //   - Explorer file rename shows no effect
    // keybd_event sends EXPLICIT keydown AND keyup for both Ctrl and V, with
    // small sleeps between events so the target app processes each one.
    const psScript = `
$code = @"
using System;
using System.Runtime.InteropServices;
public class KeySim {
  [DllImport("user32.dll")] public static extern void keybd_event(byte bVk, byte bScan, uint dwFlags, IntPtr dwExtraInfo);
  public static void CtrlV() {
    keybd_event(0x11, 0, 0, IntPtr.Zero);
    System.Threading.Thread.Sleep(15);
    keybd_event(0x56, 0, 0, IntPtr.Zero);
    System.Threading.Thread.Sleep(15);
    keybd_event(0x56, 0, 2, IntPtr.Zero);
    System.Threading.Thread.Sleep(15);
    keybd_event(0x11, 0, 2, IntPtr.Zero);
  }
}
"@
Add-Type -TypeDefinition $code
[KeySim]::CtrlV()
`;
    // -EncodedCommand accepts base64 UTF-16LE — avoids all quoting/escaping
    // issues with embedding multi-line C# in a command-line string.
    const encoded = Buffer.from(psScript, 'utf16le').toString('base64');
    exec(
      `powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -EncodedCommand ${encoded}`,
      (err) => {
        pasteInProgress = false;
        if (err) {
          console.error('Auto-paste keystroke error:', err);
          // Even on error, the text is already in the clipboard — the user
          // can press Ctrl+V manually.
        }
      }
    );
  }, 250);
}

function startMicrophone() {
  console.log(`===DIAG=== [Main PID:${process.pid}] startMicrophone() ENTERED, isRecording=${isRecording}, crispAsrProcess=${crispAsrProcess ? 'set' : 'null'}`);
  // Guard against duplicate start in the SAME main process (rapid double-click,
  // hotkey+button race, React StrictMode remount). We check ONLY isRecording:
  // a stale crispAsrProcess reference (left over after file transcription
  // completed) must NOT block mic recording — that was the bug that prevented
  // the mic from starting at all.
  if (isRecording) {
    console.log(`===DIAG=== [Main PID:${process.pid}] startMicrophone() BLOCKED by guard (already recording)`);
    return;
  }
  isRecording = true;
  interimTranscript = ""; // Reset current buffer
  tray?.setImage(REC_ICON);
  win?.webContents.send('recording-state', true);
  startCrispBackendInstance('mic');
}

function stopMicrophone() {
  // Only act if we're actually recording. A stale crispAsrProcess reference
  // (e.g. after file mode) must not trigger clipboard/toast logic here.
  if (!isRecording) {
    return;
  }
  isRecording = false;
  tray?.setImage(IDLE_ICON);
  win?.webContents.send('recording-state', false);

  if (crispAsrProcess) {
    try {
      crispAsrProcess.kill('SIGKILL');
    } catch (e) {
      console.error('Failed to kill backend on stop:', e);
    }
    crispAsrProcess = null;
  }

  const finalText = interimTranscript.trim();
  if (finalText.length === 0) {
    return;
  }

  if (settings.autoPaste || uiAutoPaste) {
    // Auto-paste mode (tray OR interface): each finalized phrase was already
    // pasted into the target app in real time. On stop, we still write the
    // FULL transcript to the clipboard as a fallback (in case some phrases
    // were dropped due to the pasteInProgress guard), and show a toast.
    clipboard.writeText(finalText);
    win?.webContents.send('show-toast', {
      message: t(curLocale(), 'toast.inserted'),
      preview: finalText.length > 60 ? finalText.slice(0, 60) + '…' : finalText
    });
  } else {
    // Normal mode: write the full transcript to the clipboard only.
    // The user pastes manually with Ctrl+V wherever they want.
    clipboard.writeText(finalText);
    win?.webContents.send('show-toast', {
      message: t(curLocale(), 'toast.copied'),
      preview: finalText.length > 60 ? finalText.slice(0, 60) + '…' : finalText
    });
  }
}

// --- IPC EVENT BINDINGS ---
ipcMain.handle('get-settings', () => settings);
ipcMain.handle('save-settings', (_e, newSettings) => {
  settings = newSettings;
  saveSettings();
  return true;
});

// Toggle auto-paste from the Settings modal / tray menu — this is the
// "auto-paste via hotkey" setting (settings.autoPaste), persisted and
// synchronized between the tray menu and the Settings modal checkbox.
ipcMain.handle('set-auto-paste', (_e, value: boolean) => {
  setAutoPaste(value);
  return settings.autoPaste;
});

// Open an external URL in the user's default browser. Used by the license
// links in the Settings modal. Restricted to http(s) for safety.
ipcMain.handle('open-external', (_e, url: string) => {
  if (typeof url === 'string' && /^https?:\/\//i.test(url)) {
    shell.openExternal(url);
  }
  return true;
});

// Toggle auto-paste from the footer UI button — this is the "interface mode"
// toggle (uiAutoPaste). INDEPENDENT of settings.autoPaste. NOT persisted, NOT
// synchronized with tray/settings. When ON, the window is NOT hidden.
ipcMain.handle('set-ui-auto-paste', (_e, value: boolean) => {
  uiAutoPaste = !!value;
  return uiAutoPaste;
});

// Clear the transcript in the UI and reset the accumulated text buffer in main.
ipcMain.handle('clear-transcript', () => {
  interimTranscript = "";
  micLastUtteranceId = -1;
  win?.webContents.send('transcription-clear');
  return true;
});

ipcMain.on('close-app', () => {
  win?.close(); // Uses 'close' preventDefault hiding
});

ipcMain.on('minimize-app', () => {
  win?.minimize();
});

ipcMain.handle('start-mic', () => {
  console.log(`===DIAG=== [Main PID:${process.pid}] IPC 'start-mic' RECEIVED at ${new Date().toISOString()}`);
  startMicrophone();
});
ipcMain.handle('stop-mic', () => {
  console.log(`===DIAG=== [Main PID:${process.pid}] IPC 'stop-mic' RECEIVED at ${new Date().toISOString()}`);
  stopMicrophone();
});

ipcMain.handle('transcribe-file', async () => {
  if (!win) return;
  const result = await dialog.showOpenDialog(win, {
    properties: ['openFile'],
    filters: [{ name: 'Audio', extensions: ['wav', 'mp3', 'ogg', 'opus'] }]
  });
  if (!result.canceled && result.filePaths.length > 0) {
    interimTranscript = "";
    startCrispBackendInstance('file', result.filePaths[0]);
  }
});

app.whenReady().then(() => {
  console.log(`===DIAG=== [Main PID:${process.pid}] app.whenReady() — Electron main process started at ${new Date().toISOString()}`);
  loadSettings();
  createWindow();
  createTray();
  registerHotkeys();
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
  if (crispAsrProcess) crispAsrProcess.kill();
});
