import { app, BrowserWindow, ipcMain, Tray, Menu, globalShortcut, clipboard, dialog, desktopCapturer, nativeImage, shell } from 'electron';
import path from 'path';
import { exec, spawn, ChildProcess } from 'child_process';
import fs from 'fs';
import * as readline from 'readline';
import * as net from 'net';
import { t, detectLocale, Locale } from '../src/i18n';

let win: BrowserWindow | null = null;
let tray: Tray | null = null;
let crispAsrProcess: ChildProcess | null = null;

let isRecording = false;
let interimTranscript = "";

// Default settings
const settingsPath = path.join(app.getPath('userData'), 'crisp_settings.json');
let settings = {
  backend: 'cpu',
  micDevice: 'default',
  threads: 4,
  gpuId: 0,
  language: 'auto',
  hotkey: 'CommandOrControl+Shift+R',
  mode: 'lowest-latency',
  autoStart: false,
  autoPaste: false,
  locale: '' as string, // interface language; detected from OS on first launch
  silenceMsLowest: 30,    // silence threshold for lowest-latency mode
  silenceMsBest: 1150     // silence threshold for best-quality mode
};

// Current interface locale (falls back to English if unset).
function curLocale(): Locale {
  return ((settings.locale as string) || 'en') as Locale;
}

// --- BASE64 ICONS FOR TRAY ---
// 32x32 Retro grille microphone. White = outline + grille slot lines + stem.
// Interior (between slots) is BLACK when idle, RED when recording.
// Generated by gen-icons.js — regenerate with: node gen-icons.js
const IDLE_ICON_B64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAASklEQVR4nO3SsQ0AMAgDQfZfOilYAEe2SPGWqDmQqwgZ5oiJGMQxbu6LpLF+4QvAS6yA9Q8AoAMA6AAAOgBgvQOrgAkqugwAgGQuS3PxKyxOok0AAAAASUVORK5CYII=";
const REC_ICON_B64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAT0lEQVR4nO3SwQkAMAhDUadx/6G6h6UbqETs4Qc8+5SYEZJMFCMHHPeojHT5u6gKkH7hC0AnUsD6BwDQAQB0AAAdALDegVVABjW6DACAyVyXDcb6Sb1OQAAAAABJRU5ErkJggg==";

const IDLE_ICON = nativeImage.createFromDataURL(IDLE_ICON_B64);
const REC_ICON = nativeImage.createFromDataURL(REC_ICON_B64);


function loadSettings() {
  if (fs.existsSync(settingsPath)) {
    try {
      const data = fs.readFileSync(settingsPath, 'utf8');
      settings = { ...settings, ...JSON.parse(data) };
      app.setLoginItemSettings({ openAtLogin: settings.autoStart });
    } catch(e) { console.error("Could not load settings", e); }
  }
  // First launch: detect the interface language from the OS locale.
  // If the Windows locale is not supported, detectLocale falls back to 'en'.
  if (!settings.locale) {
    settings.locale = detectLocale(app.getLocale());
    try { fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2)); } catch(_) {}
  }
}

function saveSettings() {
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
  app.setLoginItemSettings({ openAtLogin: settings.autoStart });
  registerHotkeys();
  // Keep the tray menu checkboxes (autoPaste, autoStart, mode radios) in sync.
  rebuildTrayMenu();
  // Notify the renderer so the UI toggle button and the settings modal
  // checkbox reflect changes made from the tray menu.
  emitSettingsUpdated();
}

// Emit the current settings to the renderer. Used whenever settings change
// from a source OTHER than the renderer itself (tray menu, hotkey, etc.) so
// the UI stays in sync.
function emitSettingsUpdated() {
  win?.webContents.send('settings-updated', { ...settings });
}

// Toggle auto-paste from a single entry point (tray menu, IPC, etc.).
// This keeps the tray checkbox, the UI toggle button, and the settings modal
// checkbox all synchronized.
function setAutoPaste(value: boolean) {
  settings.autoPaste = !!value;
  saveSettings();
}

function registerHotkeys() {
  globalShortcut.unregisterAll();
  if (settings.hotkey) {
    globalShortcut.register(settings.hotkey, () => {
      if (isRecording) {
        stopMicrophone(); // Uses same logic as clicking Stop
      } else {
        startMicrophone(); // Uses same logic as clicking Start
      }
    });
  }
}

function rebuildTrayMenu() {
  if (!tray) return;
  const L = curLocale();
  const ctxMenu = Menu.buildFromTemplate([
    { label: t(L, 'tray.open'), click: () => win?.show() },
    {
      label: t(L, 'tray.modeLowest'),
      type: 'radio',
      checked: settings.mode === 'lowest-latency',
      click: () => { settings.mode = 'lowest-latency'; saveSettings(); }
    },
    {
      label: t(L, 'tray.modeBest'),
      type: 'radio',
      checked: settings.mode === 'best-quality',
      click: () => { settings.mode = 'best-quality'; saveSettings(); }
    },
    {
      label: t(L, 'tray.modeRecord'),
      type: 'radio',
      checked: settings.mode === 'record-then-recognize',
      click: () => { settings.mode = 'record-then-recognize'; saveSettings(); }
    },
    { type: 'separator' },
    {
      label: t(L, 'tray.autoPaste'),
      type: 'checkbox',
      checked: settings.autoPaste,
      click: (item) => { setAutoPaste(item.checked); }
    },
    {
      label: t(L, 'tray.autoStart'),
      type: 'checkbox',
      checked: settings.autoStart,
      click: (item) => { settings.autoStart = item.checked; saveSettings(); }
    },
    { label: t(L, 'tray.exit'), click: () => {
      win?.destroy(); // destroy avoids the close-to-tray logic
      app.quit();
    }}
  ]);
  tray.setContextMenu(ctxMenu);
}

function createTray() {
  tray = new Tray(IDLE_ICON);
  tray.setToolTip('AutoSpeechWriter');
  rebuildTrayMenu();
  tray.on('click', () => {
    win?.isVisible() ? win.hide() : win?.show();
  });
}

function createWindow() {
  win = new BrowserWindow({
    width: 600,
    height: 700,
    frame: false,
    resizable: true,
    title: 'AutoSpeechWriter',
    icon: path.join(__dirname, '..', 'build', 'icon.png'), // app/taskbar icon (microphone)
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      backgroundThrottling: false // Keep running smartly when minimized
    }
  });

  // Depending on env, load URL or local file
  if (process.env.VITE_DEV_SERVER_URL) {
    win.loadURL(process.env.VITE_DEV_SERVER_URL);
  } else {
    win.loadFile(path.join(__dirname, '../dist/index.html'));
  }

  // Intercept close to minimize to tray
  win.on('close', (e) => {
    e.preventDefault();
    win?.hide();
  });
}

const INFO_PREFIXES = [
  "crispasr", "sensevoice", "parakeet", "whisper", "moonshine",
  "voxtral", "qwen", "canary", "auto-detected", "loading", "usage", "system memory",
  "ggml", "backend", "buffer", "model", "encoder", "decoder", "vulkan", "cuda",
  "whisper_init", "whisper_model_load", "whisper_backend", "whisper_print_timings",
  "[", "$", "=", "-", "POST", "Ping", "HTTP", "✓", "✗", "готов", "работает", 
  "запуск", "сервер", "loaded", "processing", "transcribed", "main:"
];

function isResultLine(text: string): boolean {
  if (!text) return false;
  const low = text.toLowerCase();
  for (const p of INFO_PREFIXES) {
    if (low.startsWith(p)) {
      return false;
    }
  }
  return true;
}

// When transcribing a video with subtitle mode ON, we remember the original
// video path here so that after crispasr finishes we can auto-save the SRT
// next to the video (same basename, .srt extension) — mirroring the behavior
// already in place for audio files. Cleared on every new transcription start.
let pendingVideoSrtAutoSave: string | null = null;

// In record-then-recognize mode (mode 3), the renderer records via
// MediaRecorder and sends the blob to main for transcription. Unlike mic
// streaming mode, there's no real-time partial/final — text arrives as
// file-text result lines AFTER recording stops. We accumulate the recognized
// text here so that when the backend finishes, we can perform the same
// clipboard + auto-paste behavior as streaming modes (if autoPaste is ON).
// Set to true when transcribeRecording is called from the renderer's
// record-then-recognize path.
let pendingRecordThenRecognizePaste = false;
let recordThenRecognizeText = '';

let micLastUtteranceId = -1;

// Current backend output mode. Set by startCrispBackendInstance and read by
// processAsrLogLine to decide how to interpret each stdout line.
//   'mic'       — streaming JSON (partial/final), for live microphone dictation
//   'file-text' — plain text result lines, for file transcription
//   'file-srt'  — SRT subtitle output, for file transcription with -osrt flag
let currentBackendMode: 'mic' | 'file-text' | 'file-srt' = 'mic';

// Accumulated SRT content for the current file-srt run. Sent to the UI as a
// complete string after each new line so the user sees the subtitles build up.
let srtContent = '';
// Running index for SRT entries (1-based, as per SRT spec).
let srtIndex = 0;

// Emulate backend logic processing
function processAsrLogLine(line: string, mode: 'mic' | 'file' | 'file-srt') {
  if (!win) return;

  // ---- SRT subtitle mode ----
  // crispasr with -osrt does NOT output standard SRT. It outputs lines like:
  //   [00:00:01.670 --> 00:00:16.230]  Люди достаточно хорошо замечают...
  // We parse this format and convert to standard SRT:
  //   1
  //   00:00:01,670 --> 00:00:16,230
  //   Люди достаточно хорошо замечают...
  // (note: period → comma in timestamps, per SRT spec)
  if (mode === 'file-srt') {
    const trimmed = line.trim();

    // Match the crispasr subtitle line format.
    //   ^\[  (  \d{2}:\d{2}:\d{2}\.\d{3} )  \s*-->\s*  (  \d{2}:\d{2}:\d{2}\.\d{3} )  \]\s*  (.*)$
    const tsMatch = trimmed.match(
      /^\[(\d{2}:\d{2}:\d{2}\.\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}\.\d{3})\]\s*(.*)$/
    );
    if (tsMatch) {
      const start = tsMatch[1].replace('.', ','); // SRT uses comma for ms
      const end = tsMatch[2].replace('.', ',');
      const text = tsMatch[3];
      srtIndex++;
      // Standard SRT: blank line between entries (not before the first).
      if (srtIndex > 1) srtContent += '\n';
      srtContent += `${srtIndex}\n${start} --> ${end}\n${text}\n`;
      // Send the full SRT-so-far to the UI so the user sees subtitles build up.
      win.webContents.send('transcription-update', srtContent, true);
      // Also log a compact confirmation line.
      win.webContents.send('log-update', `[SRT ${srtIndex}] ${text}\n`);
      return;
    }

    // Non-subtitle line (info/debug) — log only, don't pollute SRT content.
    // Note: we can't use isResultLine() here because it filters lines starting
    // with "[" — which is exactly the subtitle format. The regex above handles
    // subtitle detection; everything else is treated as info output.
    if (trimmed.length > 0) {
      win.webContents.send('log-update', trimmed + '\n');
    }
    return;
  }

  const trimmed = line.trim();
  if (trimmed.length === 0) return;

  if (mode === 'mic') {
    if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
      try {
        const parsed = JSON.parse(trimmed);
        
        if (parsed.type === 'silence') {
          win.webContents.send('silence-state', true);
          setTimeout(() => win?.webContents.send('silence-state', false), 1500);
          return;
        }

        if (parsed.type && parsed.text !== undefined) {
          const utteranceId = parsed.utterance_id || 0;
          const text = parsed.text.trim();
          
          if (parsed.type === 'partial') {
            win.webContents.send('transcription-update', text, false);
            return;
          } else if (parsed.type === 'final') {
            if (utteranceId > micLastUtteranceId) {
              if (text) {
                micLastUtteranceId = utteranceId;
                // Accumulate finalized text so the non-autoPaste path can copy
                // the full transcript to the clipboard when recording stops.
                interimTranscript += text + ' ';
                // Always update the UI transcript (gray partial / white final).
                win.webContents.send('transcription-update', text, true);
                win.webContents.send('log-update', `[ФИНАЛ] ${text}\n`);
                // AUTO-PASTE: fires if EITHER settings.autoPaste (tray mode)
                // OR uiAutoPaste (interface mode) is ON. The window is NEVER
                // hidden — see the comment block above executePasteIntoActiveApp.
                if (settings.autoPaste || uiAutoPaste) {
                  executePasteIntoActiveApp(text + ' ');
                }
              } else {
                win.webContents.send('transcription-update', '', false);
              }
            }
            return;
          }
        }
      } catch (e) {
        // Fall through
      }
    }
  }

  // Not JSON, or file mode
  const isRes = isResultLine(trimmed);
  if (isRes) {
    win.webContents.send('log-update', trimmed + '\n');
    // In mic mode, the transcript is driven EXCLUSIVELY by JSON partial/final
    // messages. crispasr echoes each finalized phrase both as a JSON
    // {"type":"final"} line AND as a plain-text line. If we appended the
    // plain-text echo here, every phrase would appear twice in the UI.
    if (mode !== 'mic') {
      win.webContents.send('transcription-update', trimmed, true);
      // In record-then-recognize mode, accumulate text for auto-paste when
      // the backend finishes (mirrors the streaming modes' behavior).
      if (pendingRecordThenRecognizePaste) {
        recordThenRecognizeText += trimmed + ' ';
      }
    }
  } else {
    win.webContents.send('log-update', trimmed + '\n');
  }
}

// ---------------------------------------------------------------------------
// Extract the audio track from a video file into a temporary WAV (16 kHz,
// mono, PCM s16le — exactly what crispasr expects). Uses the bundled ffmpeg.
// The callback receives the temp WAV path on success, or null on failure.
// The temp file is created in the OS temp dir and deleted on app quit.
// ---------------------------------------------------------------------------
function extractAudioFromVideo(videoPath: string, basePath: string, cb: (wavPath: string | null) => void) {
  const ffmpegBinPath = path.join(basePath, 'ffmpeg', 'bin');
  const ffmpegRootPath = path.join(basePath, 'ffmpeg');
  // Find ffmpeg.exe: prefer ffmpeg/bin, fall back to ffmpeg/ root.
  const ffmpegExe = path.join(ffmpegBinPath, process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg');
  const ffmpegAlt = path.join(ffmpegRootPath, process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg');
  const ffmpeg = fs.existsSync(ffmpegExe) ? ffmpegExe : (fs.existsSync(ffmpegAlt) ? ffmpegAlt : 'ffmpeg');

  // Temp WAV path — unique per extraction to avoid collisions.
  const tmpDir = app.getPath('temp');
  const tmpName = `asw-${Date.now()}-${Math.round(Math.random() * 1e6)}.wav`;
  const tmpWav = path.join(tmpDir, tmpName);

  const baseName = path.basename(videoPath);
  win?.webContents.send('log-update', `[SYSTEM] Extracting audio from "${baseName}" → temp WAV...\n`);

  const args = [
    '-y',               // overwrite temp file if exists
    '-i', videoPath,
    '-vn',              // no video
    '-ac', '1',         // mono
    '-ar', '16000',     // 16 kHz — crispasr's expected sample rate
    '-acodec', 'pcm_s16le', // 16-bit PCM codec
    // NOTE: do NOT pass '-f s16le' — that forces RAW PCM without a WAV/RIFF
    // header, and crispasr's miniaudio reader cannot parse it. With just the
    // .wav extension + pcm_s16le codec, ffmpeg writes a proper WAV container.
    tmpWav
  ];

  const env = buildUtf8Env([ffmpegBinPath, ffmpegRootPath]);

  try {
    const proc = spawn(ffmpeg, args, { env, windowsHide: true });
    let stderrBuf = '';
    proc.stderr?.on('data', (d: Buffer) => {
      // ffmpeg writes progress to stderr — keep it for debugging but don't
      // spam the UI log.
      stderrBuf += d.toString();
    });
    proc.on('close', (code) => {
      if (code === 0 && fs.existsSync(tmpWav)) {
        win?.webContents.send('log-update', `[SYSTEM] Audio extracted: ${tmpWav}\n`);
        // Register the temp file for cleanup on app quit.
        tempFilesToDelete.push(tmpWav);
        cb(tmpWav);
      } else {
        const tail = stderrBuf.split('\n').slice(-6).join('\n');
        console.error('ffmpeg extraction failed:', code, tail);
        win?.webContents.send('log-update', `[SYSTEM ERROR] ffmpeg audio extraction failed (code ${code}).\n${tail}\n`);
        cb(null);
      }
    });
    proc.on('error', (e) => {
      console.error('ffmpeg spawn error:', e);
      win?.webContents.send('log-update', `[SYSTEM ERROR] Cannot start ffmpeg: ${e.message}\n`);
      cb(null);
    });
  } catch (e: any) {
    console.error('ffmpeg exception:', e);
    win?.webContents.send('log-update', `[SYSTEM ERROR] ffmpeg exception: ${e.message}\n`);
    cb(null);
  }
}

// Temp files (extracted WAVs) to delete when the app quits.
const tempFilesToDelete: string[] = [];

// Build a process environment with UTF-8 forced. This fixes issues with
// Cyrillic (and other non-ASCII) characters in file paths and console output
// on Windows, where the default codepage is often cp1251. By setting
// PYTHONUTF8 / PYTHONIOENCODING / LANG / LC_ALL we ensure child processes
// (crispasr, ffmpeg) interpret paths and output as UTF-8.
function buildUtf8Env(extraPathEntries?: string[]) {
  const env = Object.assign({}, process.env);
  env.PYTHONUTF8 = '1';
  env.PYTHONIOENCODING = 'utf-8';
  env.LANG = 'en_US.UTF-8';
  env.LC_ALL = 'en_US.UTF-8';
  if (extraPathEntries && extraPathEntries.length > 0) {
    env.PATH = extraPathEntries.join(path.delimiter) + path.delimiter + (env.PATH || '');
  }
  return env;
}

// ---------------------------------------------------------------------------
// Fake-ffmpeg pipe streaming
// ---------------------------------------------------------------------------
// PROBLEM: crispasr's `-f -` (read from stdin) goes through miniaudio, which
// can't open stdin on Windows. The `--mic` mode uses a DIFFERENT code path —
// it spawns ffmpeg internally and reads raw PCM from ffmpeg's stdout. This
// streaming path gives real-time partial/final JSON output.
//
// SOLUTION: Create a "fake ffmpeg" — a .cmd wrapper that the real ffmpeg
// reads from our named pipe instead of a dshow device. We put this wrapper
// FIRST in PATH. When crispasr spawns `ffmpeg` in --mic mode, it finds our
// wrapper. The wrapper calls the real ffmpeg.exe with our named pipe as input.
//
// AUDIO FLOW:
//   Renderer (AudioWorklet) → IPC → main → named pipe →
//   fake ffmpeg.cmd → real ffmpeg.exe (passthrough) → stdout →
//   crispasr (--mic streaming path) → JSON partial/final → UI
//
// This gives TRUE continuous streaming: mixed audio flows into crispasr as
// it's formed, with full VAD context, no segment boundaries, no word cutoffs.
// ---------------------------------------------------------------------------
let pipeStreamingProcess: ChildProcess | null = null;
let pipeServer: net.Server | null = null;
let pipeConn: net.Socket | null = null;
let pipeBuffer: Buffer[] = [];
let streamingActive = false;
let ffmpegWrapperDir: string | null = null;
const STREAMING_SAMPLE_RATE = 16000;

function startPipeStreaming(silenceMs: number) {
  const basePath = app.isPackaged ? process.resourcesPath : path.join(__dirname, '..');
  const dirName = `crispasr-windows-x86_64-${settings.backend}`;
  const binPath = path.join(basePath, dirName, 'crispasr.exe');
  const modelPath = path.join(basePath, 'models-cache', 'parakeet-tdt-0.6b-v3-q4_k.gguf');

  // Find the real ffmpeg
  const ffmpegBinPath = path.join(basePath, 'ffmpeg', 'bin');
  const ffmpegRootPath = path.join(basePath, 'ffmpeg');
  const ffmpegExe = path.join(ffmpegBinPath, process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg');
  const ffmpegAlt = path.join(ffmpegRootPath, process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg');
  const realFfmpeg = fs.existsSync(ffmpegExe) ? ffmpegExe : (fs.existsSync(ffmpegAlt) ? ffmpegAlt : 'ffmpeg');

  if (!fs.existsSync(binPath)) {
    win?.webContents.send('log-update', `[SYSTEM ERROR] Backend binary not found: ${binPath}\n`);
    win?.webContents.send('recording-state', false);
    win?.webContents.send('backend-finished');
    return;
  }

  // Create a unique named pipe path (Windows format: \\.\pipe\name)
  const pipeName = `\\\\.\\pipe\\asw-audio-${Date.now()}`;

  // Create a temp directory for the fake ffmpeg wrapper
  ffmpegWrapperDir = path.join(app.getPath('temp'), `asw-ffmpeg-${Date.now()}-${Math.round(Math.random() * 1e6)}`);
  fs.mkdirSync(ffmpegWrapperDir, { recursive: true });

  // Write the ffmpeg.cmd wrapper. It IGNORES all arguments passed by crispasr
  // (the dshow device args) and instead reads raw s16le 16kHz mono PCM from
  // our named pipe, outputting the same format to stdout.
  // -probesize 32 -analyzeduration 0: skip probing (raw PCM doesn't need it)
  // -fflags +nobuffer: minimize buffering for low latency
  const wrapperPath = path.join(ffmpegWrapperDir, 'ffmpeg.cmd');
  const wrapperContent = `@echo off\r\n"${realFfmpeg}" -probesize 32 -analyzeduration 0 -fflags +nobuffer -f s16le -ar 16000 -ac 1 -i "${pipeName}" -f s16le -ar 16000 -ac 1 -`;
  fs.writeFileSync(wrapperPath, wrapperContent, 'utf8');

  // Create the named pipe server
  pipeBuffer = [];
  pipeConn = null;
  pipeServer = net.createServer((conn) => {
    pipeConn = conn;
    // Flush any buffered PCM data that arrived before ffmpeg connected
    for (const buf of pipeBuffer) {
      conn.write(buf);
    }
    pipeBuffer = [];
    conn.on('close', () => { pipeConn = null; });
    conn.on('error', () => { pipeConn = null; });
  });
  pipeServer.on('error', (err) => {
    win?.webContents.send('log-update', `[SYSTEM ERROR] Named pipe error: ${err.message}\n`);
  });
  pipeServer.listen(pipeName);

  // Build crispasr args — use --mic mode (the streaming code path)
  const args = [
    '-m', modelPath,
    '-t', settings.threads.toString(),
    '-dev', settings.gpuId.toString()
  ];
  if (settings.language) args.push('-l', settings.language);
  args.push('--mic');
  args.push('--stream-json');
  args.push('--vad');
  args.push('--stream-final-on-silence-ms', silenceMs.toString());

  currentBackendMode = 'mic';
  micLastUtteranceId = -1;
  interimTranscript = "";

  // PATH: our wrapper dir MUST be first so crispasr finds ffmpeg.cmd
  // before the real ffmpeg.exe. UTF-8 env fixes Cyrillic path issues.
  const env = buildUtf8Env([ffmpegWrapperDir, ffmpegBinPath, ffmpegRootPath]);

  win?.webContents.send('log-update', `[SYSTEM] Starting pipe streaming (fake-ffmpeg wrapper):\n[SYSTEM]   ${binPath}\n[SYSTEM]   Args: ${args.join(' ')}\n[SYSTEM]   Pipe: ${pipeName}\n[SYSTEM]   Wrapper: ${wrapperPath}\n`);

  try {
    pipeStreamingProcess = spawn(binPath, args, {
      cwd: path.dirname(binPath),
      env,
      windowsHide: true
    });
  } catch (e: any) {
    cleanupPipeStreaming();
    win?.webContents.send('log-update', `[SYSTEM ERROR] Pipe streaming spawn failed: ${e.message}\n`);
    win?.webContents.send('recording-state', false);
    win?.webContents.send('backend-finished');
    return;
  }

  streamingActive = true;

  if (pipeStreamingProcess.stdout) {
    const rl = readline.createInterface({ input: pipeStreamingProcess.stdout, crlfDelay: Infinity });
    rl.on('line', (line: string) => {
      processAsrLogLine(line, 'mic');
    });
  }
  pipeStreamingProcess.stderr?.on('data', (d: Buffer) => {
    const msg = d.toString().trim();
    if (msg) win?.webContents.send('log-update', `[LOG] ${msg}\n`);
  });

  pipeStreamingProcess.on('close', (code) => {
    win?.webContents.send('log-update', `[SYSTEM] Pipe streaming process exited (code ${code}).\n`);
    pipeStreamingProcess = null;
    streamingActive = false;
    cleanupPipeStreaming();
    tray?.setImage(IDLE_ICON);
    win?.webContents.send('recording-state', false);
    win?.webContents.send('backend-finished');
  });
  pipeStreamingProcess.on('error', (e) => {
    win?.webContents.send('log-update', `[SYSTEM ERROR] Pipe streaming error: ${e.message}\n`);
  });

  tray?.setImage(REC_ICON);
  win?.webContents.send('recording-state', true);
}

// Write a Float32 PCM chunk to the named pipe (→ fake ffmpeg → crispasr)
function writePcmToPipe(chunk: Float32Array) {
  if (!streamingActive || !chunk) return;
  // Convert Float32 (-1..1) to Int16 s16le
  const buf = Buffer.alloc(chunk.length * 2);
  for (let i = 0; i < chunk.length; i++) {
    const s = Math.max(-1, Math.min(1, chunk[i]));
    buf.writeInt16LE(Math.round(s * 32767), i * 2);
  }
  if (pipeConn && !pipeConn.destroyed) {
    pipeConn.write(buf);
  } else {
    // Buffer until ffmpeg connects to the named pipe
    pipeBuffer.push(buf);
  }
}

// Stop pipe streaming: close the pipe (EOF) → ffmpeg finishes → crispasr finishes
function stopPipeStreaming() {
  streamingActive = false;
  if (pipeConn && !pipeConn.destroyed) {
    pipeConn.end(); // Signal EOF to ffmpeg
  }
  pipeConn = null;
}

// Clean up pipe streaming resources (named pipe server + wrapper dir)
function cleanupPipeStreaming() {
  if (pipeConn) { try { pipeConn.destroy(); } catch (_) {} pipeConn = null; }
  if (pipeServer) { try { pipeServer.close(); } catch (_) {} pipeServer = null; }
  if (ffmpegWrapperDir) {
    try { fs.rmSync(ffmpegWrapperDir, { recursive: true, force: true }); } catch (_) {}
    ffmpegWrapperDir = null;
  }
  pipeBuffer = [];
}

function startCrispBackendInstance(mode: 'file' | 'mic', payload?: string, subtitleMode: boolean = false) {
  // Guard: if a backend process is already running, kill it synchronously and
  // clear the reference BEFORE spawning a new one. This prevents two parallel
  // crispasr.exe instances from grabbing the microphone simultaneously
  // (which was the root cause of duplicated final text).
  if (crispAsrProcess) {
    try {
      crispAsrProcess.kill('SIGKILL');
    } catch (e) {
      console.error('Failed to kill previous backend:', e);
    }
    crispAsrProcess = null;
  }

  // Construct binary paths based on requested backend settings mapping
  const basePath = app.isPackaged ? process.resourcesPath : path.join(__dirname, '..');
  const dirName = `crispasr-windows-x86_64-${settings.backend}`;
  const binPath = path.join(basePath, dirName, 'crispasr.exe');
  const modelPath = path.join(basePath, 'models-cache', 'parakeet-tdt-0.6b-v3-q4_k.gguf');
  const ffmpegBinPath = path.join(basePath, 'ffmpeg', 'bin');
  const ffmpegRootPath = path.join(basePath, 'ffmpeg');

  // Video files: extract the audio track to a temporary WAV first, because
  // crispasr only accepts audio input. We use the bundled ffmpeg.
  const videoExts = ['.mp4', '.avi', '.mov', '.mkv', '.webm', '.flv', '.wmv', '.m4v', '.mpg', '.mpeg', '.ts', '.3gp'];
  if (mode === 'file' && payload) {
    const ext = path.extname(payload).toLowerCase();
    if (videoExts.includes(ext)) {
      // If subtitle mode is ON, remember the original video path so we can
      // auto-save the generated SRT next to it after transcription finishes.
      pendingVideoSrtAutoSave = subtitleMode ? payload : null;
      // Defer to the async extractor, which will call startCrispBackendInstance
      // again with the extracted WAV path once extraction succeeds.
      extractAudioFromVideo(payload, basePath, (wavPath) => {
        if (wavPath) {
          startCrispBackendInstance(mode, wavPath, subtitleMode);
        } else {
          // Extraction failed — error already logged + UI notified.
          pendingVideoSrtAutoSave = null;
          win?.webContents.send('backend-finished');
        }
      });
      return;
    } else {
      // Non-video file: no auto-save pending.
      pendingVideoSrtAutoSave = null;
    }
  }

  // Verify binary exists, fallback to simulating the logic if path missing in dev
  if (!fs.existsSync(binPath)) {
    console.log(`[SIMULATED ASR] Backend binary not found at ${binPath}. Simulating output.`);
    win?.webContents.send('log-update', `[SYSTEM] Backend not found at ${binPath}\n`);
    // Dev only mock streaming
    setTimeout(() => { processAsrLogLine('{"type":"silence","t":1.000}', mode); }, 1000);
    setTimeout(() => { processAsrLogLine('Recognized test transcription.', mode); stopMicrophone(); }, 3000);
    return;
  }

  const args = [
    '-m', modelPath,
    '-t', settings.threads.toString(),
    '-dev', settings.gpuId.toString()
  ];

  if (settings.language) {
    args.push('-l', settings.language);
  }

  // --- Output format & mode-specific flags ---
  if (mode === 'file' && subtitleMode) {
    // SRT subtitle mode: use -osrt so crispasr emits SRT with timestamps.
    // Do NOT use --stream-json (would conflict with -osrt).
    // --vad segments speech into phrases.
    // --chunk-seconds forces crispasr to split long audio into chunks for
    // processing — this produces more, shorter SRT entries instead of one
    // giant entry covering the whole video. 15s chunks balance granularity
    // and model context (parakeet handles 15s well).
    args.push('--vad');
    args.push('--chunk-seconds', '15');
    args.push('-osrt');
    // Set the backend mode so processAsrLogLine knows to collect SRT content.
    currentBackendMode = 'file-srt';
    srtContent = ''; // reset for this run
    srtIndex = 0;   // reset SRT entry counter
  } else {
    // Mic mode or plain-text file mode: use streaming JSON for parseable output.
    args.push('--stream-json');
    // VAD is REQUIRED for phrase segmentation: without it the backend cannot
    // detect phrase boundaries and will never emit {type:"final"} messages.
    args.push('--vad');
    // Silence threshold for finalizing a phrase (mic only; file doesn't use it
    // but passing it is harmless since the file isn't streamed).
    if (mode === 'mic') {
      const silenceMs = settings.mode === 'lowest-latency'
        ? (settings.silenceMsLowest ?? 30)
        : (settings.silenceMsBest ?? 1150);
      args.push('--stream-final-on-silence-ms', silenceMs.toString());
    }
    currentBackendMode = mode === 'mic' ? 'mic' : 'file-text';
  }

  if (mode === 'mic') {
    // Use --mic (phrase-by-phrase with VAD) instead of --live (continuous).
    args.push('--mic');
    micLastUtteranceId = -1;
  } else if (mode === 'file' && payload) {
    args.push('-f', payload);
  }

  win?.webContents.send('log-update', `[SYSTEM] Starting backend: ${binPath} \n[SYSTEM] Args: ${args.join(' ')}\n`);

  try {
    const env = buildUtf8Env([ffmpegBinPath, ffmpegRootPath]);

    console.log(`===DIAG=== [Main PID:${process.pid}] about to spawn crispasr.exe (mode=${mode})`);
    crispAsrProcess = spawn(binPath, args, {
      cwd: path.dirname(binPath),
      env: env
    });
    const childPid = crispAsrProcess.pid;
    console.log(`===DIAG=== [Main PID:${process.pid}] SPAWNED crispasr.exe child PID=${childPid}`);
    
    if (crispAsrProcess.stdout) {
      // Use readline so that JSON lines split across chunk boundaries are
      // correctly reassembled. The previous data.split('\n') approach silently
      // dropped any line that happened to span two 'data' events — which
      // disproportionately affected longer 'final' messages.
      const rl = readline.createInterface({
        input: crispAsrProcess.stdout,
        crlfDelay: Infinity
      });
      rl.on('line', (line: string) => {
        // Pass the resolved backend mode (which may be 'file-srt' when
        // subtitleMode is on) so processAsrLogLine interprets output correctly.
        const lineMode: 'mic' | 'file' | 'file-srt' =
          currentBackendMode === 'file-srt' ? 'file-srt' : mode;
        processAsrLogLine(line, lineMode);
      });
    }
    
    crispAsrProcess.stderr?.on('data', (err) => {
      const msg = err.toString();
      console.log('Backend Error:', msg);
      // Send backend errors to UI so user knows what's failing!
      win?.webContents.send('log-update', `[LOG] ${msg}`);
    });
    
    crispAsrProcess.on('close', (code) => {
      console.log(`===DIAG=== [Main PID:${process.pid}] child PID=${childPid} EXITED code=${code}`);
      console.log(`Backend process exited with code ${code}`);
      // Clear the reference so a future start (mic or file) isn't blocked by
      // a stale pointer to a dead process.
      crispAsrProcess = null;
      win?.webContents.send('log-update', `\n[SYSTEM] Backend process exited with code ${code}\n`);
      // Auto-save SRT next to the original video if this was a video
      // transcription with subtitle mode ON. The SRT content was accumulated
      // in `srtContent` by processAsrLogLine (file-srt mode).
      if (pendingVideoSrtAutoSave && srtContent) {
        try {
          const videoExt = path.extname(pendingVideoSrtAutoSave);
          const srtPath = pendingVideoSrtAutoSave.slice(0, -videoExt.length) + '.srt';
          fs.writeFileSync(srtPath, srtContent, 'utf8');
          win?.webContents.send('log-update', `[SYSTEM] Subtitles auto-saved: ${srtPath}\n`);
        } catch (e: any) {
          win?.webContents.send('log-update', `[SYSTEM ERROR] Failed to auto-save subtitles: ${e.message}\n`);
        }
        pendingVideoSrtAutoSave = null;
      } else {
        pendingVideoSrtAutoSave = null;
      }
      // Record-then-recognize auto-paste: if this transcription came from
      // mode 3 (MediaRecorder → blob → file), and autoPaste is enabled, write
      // the full recognized text to the clipboard and emulate Ctrl+V — the
      // same behavior as streaming modes when recording stops.
      if (pendingRecordThenRecognizePaste) {
        const finalText = recordThenRecognizeText.trim();
        if (finalText.length > 0) {
          clipboard.writeText(finalText);
          if (settings.autoPaste || uiAutoPaste) {
            executePasteIntoActiveApp(finalText);
            win?.webContents.send('show-toast', {
              message: t(curLocale(), 'toast.inserted'),
              preview: finalText.length > 60 ? finalText.slice(0, 60) + '…' : finalText
            });
          } else {
            win?.webContents.send('show-toast', {
              message: t(curLocale(), 'toast.copied'),
              preview: finalText.length > 60 ? finalText.slice(0, 60) + '…' : finalText
            });
          }
        }
        pendingRecordThenRecognizePaste = false;
        recordThenRecognizeText = '';
      }
      // Notify the UI that the backend finished (used by file mode to clear
      // isProcessing and re-enable the editable transcript).
      win?.webContents.send('backend-finished');
      // Stop recording UI state if it died
      if (isRecording) {
        stopMicrophone();
      }
    });
    
  } catch(e: any) {
    console.error("Failed to spawn CrispASR:", e);
    win?.webContents.send('log-update', `\n[SYSTEM ERROR] Failed to spawn process: ${e.message}\n`);
  }
}

// ---------------------------------------------------------------------------
// AUTO-PASTE: writes text to the clipboard and emulates Ctrl+V so the text
// lands in whatever application currently has the keyboard focus.
//
// Two INDEPENDENT triggers control whether auto-paste fires per finalized
// phrase:
//   1. settings.autoPaste — "tray mode". Synchronized between the tray menu
//                           checkbox and the Settings modal checkbox.
//   2. uiAutoPaste        — "interface mode". Toggled by the footer button
//                           in the main UI. INDEPENDENT of settings.autoPaste.
//
// Auto-paste fires if EITHER is ON. The Electron window is NEVER hidden here:
//   - If the app is in the tray, there is nothing to hide.
//   - If the user is pasting from the visible window, they want it visible
//     (e.g. to watch the gray partial text). They manage focus themselves —
//     either minimize, or just click into the target app and place the cursor.
// ---------------------------------------------------------------------------
let pasteInProgress = false;
let uiAutoPaste = false;

function executePasteIntoActiveApp(text: string) {
  if (!text) return;
  // Prevent overlapping paste operations: if a previous paste is still in
  // flight, drop this one (the next final will paste the accumulated text).
  if (pasteInProgress) {
    console.log('===DIAG=== paste already in progress, skipping');
    return;
  }
  pasteInProgress = true;

  // Step 1: write to clipboard (100% reliable, native Electron API).
  clipboard.writeText(text);

  // Step 2: wait briefly, then send Ctrl+V to whatever app currently has focus.
  // (The window is intentionally NOT hidden — see the comment block above.)
  setTimeout(() => {
    // Use keybd_event via P/Invoke instead of WScript.Shell.SendKeys.
    // SendKeys is known to leave the Ctrl modifier "stuck" — it sends keydown
    // but the keyup is unreliable, so Ctrl stays logically pressed. Symptoms:
    //   - Notepad caret stops blinking (caret stays solid while Ctrl held)
    //   - Firefox shows its F7 caret-browsing prompt instead of pasting
    //   - Explorer file rename shows no effect
    // keybd_event sends EXPLICIT keydown AND keyup for both Ctrl and V, with
    // small sleeps between events so the target app processes each one.
    const psScript = `
$code = @"
using System;
using System.Runtime.InteropServices;
public class KeySim {
  [DllImport("user32.dll")] public static extern void keybd_event(byte bVk, byte bScan, uint dwFlags, IntPtr dwExtraInfo);
  public static void CtrlV() {
    keybd_event(0x11, 0, 0, IntPtr.Zero);
    System.Threading.Thread.Sleep(15);
    keybd_event(0x56, 0, 0, IntPtr.Zero);
    System.Threading.Thread.Sleep(15);
    keybd_event(0x56, 0, 2, IntPtr.Zero);
    System.Threading.Thread.Sleep(15);
    keybd_event(0x11, 0, 2, IntPtr.Zero);
  }
}
"@
Add-Type -TypeDefinition $code
[KeySim]::CtrlV()
`;
    // -EncodedCommand accepts base64 UTF-16LE — avoids all quoting/escaping
    // issues with embedding multi-line C# in a command-line string.
    const encoded = Buffer.from(psScript, 'utf16le').toString('base64');
    exec(
      `powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -EncodedCommand ${encoded}`,
      (err) => {
        pasteInProgress = false;
        if (err) {
          console.error('Auto-paste keystroke error:', err);
          // Even on error, the text is already in the clipboard — the user
          // can press Ctrl+V manually.
        }
      }
    );
  }, 250);
}

function startMicrophone() {
  console.log(`===DIAG=== [Main PID:${process.pid}] startMicrophone() ENTERED, isRecording=${isRecording}, crispAsrProcess=${crispAsrProcess ? 'set' : 'null'}`);
  // Guard against duplicate start in the SAME main process (rapid double-click,
  // hotkey+button race, React StrictMode remount). We check ONLY isRecording:
  // a stale crispAsrProcess reference (left over after file transcription
  // completed) must NOT block mic recording — that was the bug that prevented
  // the mic from starting at all.
  if (isRecording) {
    console.log(`===DIAG=== [Main PID:${process.pid}] startMicrophone() BLOCKED by guard (already recording)`);
    return;
  }
  isRecording = true;
  interimTranscript = ""; // Reset current buffer
  tray?.setImage(REC_ICON);
  win?.webContents.send('recording-state', true);
  startCrispBackendInstance('mic');
}

function stopMicrophone() {
  // Only act if we're actually recording. A stale crispAsrProcess reference
  // (e.g. after file mode) must not trigger clipboard/toast logic here.
  if (!isRecording) {
    return;
  }
  isRecording = false;
  tray?.setImage(IDLE_ICON);
  win?.webContents.send('recording-state', false);

  if (crispAsrProcess) {
    try {
      crispAsrProcess.kill('SIGKILL');
    } catch (e) {
      console.error('Failed to kill backend on stop:', e);
    }
    crispAsrProcess = null;
  }

  const finalText = interimTranscript.trim();
  if (finalText.length === 0) {
    return;
  }

  if (settings.autoPaste || uiAutoPaste) {
    // Auto-paste mode (tray OR interface): each finalized phrase was already
    // pasted into the target app in real time. On stop, we still write the
    // FULL transcript to the clipboard as a fallback (in case some phrases
    // were dropped due to the pasteInProgress guard), and show a toast.
    clipboard.writeText(finalText);
    win?.webContents.send('show-toast', {
      message: t(curLocale(), 'toast.inserted'),
      preview: finalText.length > 60 ? finalText.slice(0, 60) + '…' : finalText
    });
  } else {
    // Normal mode: write the full transcript to the clipboard only.
    // The user pastes manually with Ctrl+V wherever they want.
    clipboard.writeText(finalText);
    win?.webContents.send('show-toast', {
      message: t(curLocale(), 'toast.copied'),
      preview: finalText.length > 60 ? finalText.slice(0, 60) + '…' : finalText
    });
  }
}

// --- IPC EVENT BINDINGS ---
ipcMain.handle('get-settings', () => settings);
ipcMain.handle('save-settings', (_e, newSettings) => {
  settings = newSettings;
  saveSettings();
  return true;
});

// Toggle auto-paste from the Settings modal / tray menu — this is the
// "auto-paste via hotkey" setting (settings.autoPaste), persisted and
// synchronized between the tray menu and the Settings modal checkbox.
ipcMain.handle('set-auto-paste', (_e, value: boolean) => {
  setAutoPaste(value);
  return settings.autoPaste;
});

// Open an external URL in the user's default browser. Used by the license
// links in the Settings modal. Restricted to http(s) for safety.
ipcMain.handle('open-external', (_e, url: string) => {
  if (typeof url === 'string' && /^https?:\/\//i.test(url)) {
    shell.openExternal(url);
  }
  return true;
});

// Toggle auto-paste from the footer UI button — this is the "interface mode"
// toggle (uiAutoPaste). INDEPENDENT of settings.autoPaste. NOT persisted, NOT
// synchronized with tray/settings. When ON, the window is NOT hidden.
ipcMain.handle('set-ui-auto-paste', (_e, value: boolean) => {
  uiAutoPaste = !!value;
  return uiAutoPaste;
});

// Clear the transcript in the UI and reset the accumulated text buffer in main.
ipcMain.handle('clear-transcript', () => {
  interimTranscript = "";
  micLastUtteranceId = -1;
  win?.webContents.send('transcription-clear');
  return true;
});

ipcMain.on('close-app', () => {
  win?.close(); // Uses 'close' preventDefault hiding
});

ipcMain.on('minimize-app', () => {
  win?.minimize();
});

ipcMain.handle('start-mic', () => {
  console.log(`===DIAG=== [Main PID:${process.pid}] IPC 'start-mic' RECEIVED at ${new Date().toISOString()}`);
  startMicrophone();
});
ipcMain.handle('stop-mic', () => {
  console.log(`===DIAG=== [Main PID:${process.pid}] IPC 'stop-mic' RECEIVED at ${new Date().toISOString()}`);
  stopMicrophone();
});

// --- Pipe streaming IPC (continuous PCM → crispasr stdin → real-time text) --
ipcMain.handle('start-pipe-streaming', (_e, silenceMs: number) => {
  startPipeStreaming(silenceMs);
});

ipcMain.on('send-pcm-pipe', (_e, chunk: Float32Array) => {
  if (!streamingActive || !chunk) return;
  writePcmToPipe(chunk);
});

ipcMain.handle('stop-pipe-streaming', () => {
  stopPipeStreaming();
});

ipcMain.handle('transcribe-file', async (_e, subtitleMode: boolean = false) => {
  if (!win) return;
  const result = await dialog.showOpenDialog(win, {
    properties: ['openFile'],
    filters: [
      { name: 'Media (Audio & Video)', extensions: [
        'wav', 'mp3', 'ogg', 'opus', 'm4a', 'flac', 'aac', 'wma', 'aiff',
        'mp4', 'avi', 'mov', 'mkv', 'webm', 'flv', 'wmv', 'm4v', 'mpg', 'mpeg', 'ts', '3gp'
      ] },
      { name: 'All files', extensions: ['*'] }
    ]
  });
  if (!result.canceled && result.filePaths.length > 0) {
    interimTranscript = "";
    startCrispBackendInstance('file', result.filePaths[0], subtitleMode);
  }
});

// Return available desktop/screen sources for system-audio loopback capture
// via desktopCapturer. The renderer uses the source id with
// getUserMedia({ audio: { chromeMediaSource: 'desktop' } }).
ipcMain.handle('get-desktop-sources', async () => {
  try {
    const sources = await desktopCapturer.getSources({ types: ['screen'], fetchWindowIcons: false });
    return sources.map(s => ({ id: s.id, name: s.name }));
  } catch (e: any) {
    console.error('desktopCapturer error:', e);
    return [];
  }
});

// Transcribe a recorded audio blob produced by the renderer's mixer
// (MediaRecorder output, typically audio/webm;codecs=opus). We write the blob
// to a temp file, convert it to WAV (16 kHz mono s16le) with the bundled
// ffmpeg, then run crispasr on the WAV. Results stream back to the UI via the
// usual transcription-update events (file-text mode).
// The `autoPaste` flag indicates this came from record-then-recognize mode
// and the recognized text should be auto-pasted (if settings.autoPaste or
// uiAutoPaste is ON) when the backend finishes — mirroring streaming modes.
ipcMain.handle('transcribe-recording', async (_e, buffer: ArrayBuffer, autoPaste: boolean = false) => {
  pendingRecordThenRecognizePaste = autoPaste;
  recordThenRecognizeText = '';
  if (!buffer || buffer.byteLength === 0) {
    win?.webContents.send('log-update', '[SYSTEM ERROR] Empty recording buffer.\n');
    win?.webContents.send('backend-finished');
    return { success: false, error: 'empty' };
  }
  const basePath = app.isPackaged ? process.resourcesPath : path.join(__dirname, '..');
  const tmpDir = app.getPath('temp');
  const stamp = `${Date.now()}-${Math.round(Math.random() * 1e6)}`;
  const inPath = path.join(tmpDir, `asw-rec-${stamp}.webm`);
  const wavPath = path.join(tmpDir, `asw-rec-${stamp}.wav`);

  try {
    fs.writeFileSync(inPath, Buffer.from(buffer));
  } catch (e: any) {
    win?.webContents.send('log-update', `[SYSTEM ERROR] Cannot write temp recording: ${e.message}\n`);
    win?.webContents.send('backend-finished');
    return { success: false, error: e.message };
  }

  // Convert webm → wav (16 kHz mono s16le) via bundled ffmpeg.
  await new Promise<void>((resolve) => {
    const ffmpegBinPath = path.join(basePath, 'ffmpeg', 'bin');
    const ffmpegRootPath = path.join(basePath, 'ffmpeg');
    const ffmpegExe = path.join(ffmpegBinPath, process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg');
    const ffmpegAlt = path.join(ffmpegRootPath, process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg');
    const ffmpeg = fs.existsSync(ffmpegExe) ? ffmpegExe : (fs.existsSync(ffmpegAlt) ? ffmpegAlt : 'ffmpeg');
    const args = ['-y', '-i', inPath, '-vn', '-ac', '1', '-ar', '16000', '-acodec', 'pcm_s16le', wavPath];
    const env = buildUtf8Env([ffmpegBinPath, ffmpegRootPath]);
    win?.webContents.send('log-update', `[SYSTEM] Converting recording → WAV...\n`);
    const proc = spawn(ffmpeg, args, { env, windowsHide: true });
    let stderrBuf = '';
    proc.stderr?.on('data', (d: Buffer) => { stderrBuf += d.toString(); });
    proc.on('close', (code) => {
      if (code === 0 && fs.existsSync(wavPath)) {
        tempFilesToDelete.push(inPath, wavPath);
        resolve();
      } else {
        const tail = stderrBuf.split('\n').slice(-6).join('\n');
        win?.webContents.send('log-update', `[SYSTEM ERROR] ffmpeg recording conversion failed (code ${code}).\n${tail}\n`);
        try { fs.unlinkSync(inPath); } catch (_) {}
        resolve();
      }
    });
    proc.on('error', (e) => {
      win?.webContents.send('log-update', `[SYSTEM ERROR] ffmpeg spawn: ${e.message}\n`);
      resolve();
    });
  });

  if (!fs.existsSync(wavPath)) {
    win?.webContents.send('backend-finished');
    return { success: false, error: 'conversion failed' };
  }

  // Run crispasr on the WAV (file-text mode → progressive transcription-update).
  startCrispBackendInstance('file', wavPath, false);
  return { success: true };
});

// Save SRT subtitles. The save dialog allows the user to either type a new
// filename OR click an existing video file — in the latter case the .srt is
// saved next to the video with the same basename.
ipcMain.handle('save-srt', async (_e, srtContent: string) => {
  if (!win) return { success: false, error: 'no window' };
  const result = await dialog.showSaveDialog(win, {
    title: 'Save subtitles',
    defaultPath: 'subtitles.srt',
    filters: [
      { name: 'Subtitles', extensions: ['srt'] },
      { name: 'Video files', extensions: ['mp4', 'avi', 'mov', 'mkv', 'webm', 'flv', 'wmv', 'm4v', 'mpg', 'mpeg', 'ts', '3gp'] }
    ]
  });
  if (result.canceled || !result.filePath) return { success: false };

  let savePath = result.filePath;
  const ext = path.extname(savePath).toLowerCase();
  const videoExts = ['.mp4', '.avi', '.mov', '.mkv', '.webm', '.flv', '.wmv', '.m4v', '.mpg', '.mpeg', '.ts', '.3gp'];
  if (videoExts.includes(ext)) {
    // User clicked a video file → replace its extension with .srt
    savePath = savePath.slice(0, -ext.length) + '.srt';
  } else if (ext !== '.srt') {
    savePath = savePath + '.srt';
  }

  try {
    fs.writeFileSync(savePath, srtContent, 'utf8');
    return { success: true, path: savePath };
  } catch (e: any) {
    return { success: false, error: e.message };
  }
});

app.whenReady().then(() => {
  console.log(`===DIAG=== [Main PID:${process.pid}] app.whenReady() — Electron main process started at ${new Date().toISOString()}`);
  loadSettings();
  createWindow();
  createTray();
  registerHotkeys();
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
  if (crispAsrProcess) crispAsrProcess.kill();
  if (pipeStreamingProcess) {
    stopPipeStreaming();
    try { pipeStreamingProcess.kill('SIGKILL'); } catch (_) {}
  }
  cleanupPipeStreaming();
  // Clean up temp WAV files extracted from videos.
  for (const f of tempFilesToDelete) {
    try { fs.unlinkSync(f); } catch (_) { /* ignore */ }
  }
});
